hydra:
    searchpath:
        - file://extra/conf/global

defaults:
    - _self_
    - dataset@_global_: cube
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog
    - override hydra/launcher: custom_slurm

agent:
    gamma: 1.0
    lmbda: 0.75 # gives largest weight to 4-step return
device: cuda
seed: 42
