hydra:
  searchpath:
    - file://extra/conf

defaults:
  - dataset_generation/dataset@dataset: ???
  - _self_

save_path: ???
instance_indices: [0, 1, 2, 3, 4]
seeds: [42, 43, 44, 45, 46]
split_ratio:
  train: 0.6
  val: 0.2
  test: 0.2
# Add this later
# - override global/hydra/job_logging@hydra/job_logging: colorlog
# - override hydra/hydra_logging: colorlog
# - override hydra/launcher: custom_slurm
