hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - dataset: imagenette
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

data_dir: "data"
split_idx: 1
seeds:
  - 42
  - 123
  - 456
  - 789
  - 101112
  - 131415
  - 161718
  - 192021
  - 222324
  - 252627
# split_ratio:
#   train: 0.7
#   val: 0.15
#   test: 0.15
split_ratio:
  train: 0.9
  val: 0.1
  test: 0.0
output_artifact_aliases: []
epsilon: 1e-8

