hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - dataset: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

data_dir: "extra"
split_idx: [1,2,3,4,5]
seeds: [42]
split_ratio:
  train: 0.7
  val: 0.15
  test: 0.15
epsilon: 1e-8
