hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - _self_
  - components/initializers@initializer: ???
  - components/unmaskers@unmasker: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

method_bundle_path: ???
# unmasker set as component
# initializer set as component
dataset_bundle_path: ???
save_path: ???
classifier_bundle_path: null
seed: null
device: "cpu"
eval_only_n_samples: null
batch_size: 1
hard_budget: null
use_wandb: false
