hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

aco:
  k_neighbors: 5
  acquisition_cost: 0.05
  hide_val: 10.0
  evaluate_final_performance: true
  eval_only_n_samples: null

seed: 42
device: "cpu"
cost_param: null
hard_budget: null
dataset_artifact_name: "cube_split_1"
