hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global
    - file://extra/conf/scripts/pretrain/shim2018

defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

train_dataset_bundle_path: ???
val_dataset_bundle_path: ???
save_path: ???
device: cuda
seed: null

batch_size: 128 # shim2018 paper
epochs: ???
limit_train_batches: null
limit_val_batches: null
lr: 1e-3
min_masking_probability: 0.1
max_masking_probability: 0.9
encoder:
  output_size: 16 # shim2018 paper
  reading_block_cells: [32, 32] # shim2018 paper
  writing_block_cells: [32, 32] # not specified by shim2018 paper, assume it is the same as reading_block_cells
  memory_size: 16 # shim2018 paper
  processing_steps: 5 # original set encoding paper
  dropout: 0.0
classifier:
  num_cells: [32, 32] # shim2018 paper (cube dataset)
use_wandb: false
