hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm


trained_method_artifact_name: ""
trained_classifier_artifact_name: ""
seed: 42
device: "cuda"
eval_only_n_samples: null
batch_size: 1
dataset_split: "testing"
experiment_id: ""
