hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

dataset_base_path: "extra/data/datasets"
output_dir: "extra/result/covert2023/pretrain"
device: cuda
seed: 42
