hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

train_dataset_path: ???
val_dataset_path: ???
save_path: ???

epochs: 100
batch_size: 128
limit_train_batches: null
limit_val_batches: null
min_masking_probability: 0.0
max_masking_probability: 0.9

initializer:
  class_name: "ZeroInitializer"
  kwargs: {}

unmasker:
  class_name: "DirectUnmasker"
  kwargs: {}

eval_only_n_samples: null


lr: 1e-3
num_cells: [128, 128]
dropout: 0.1

seed: 42
device: "cuda"
