hydra:
    searchpath:
        - file://extra/conf/global

defaults:
    - _self_
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog
    - override hydra/launcher: custom_slurm

trained_method_artifact_name: "dummy-cube_split_1-param1-seed_42:tmp"
cost_param: null
trained_classifier_artifact_name: "masked_mlp_classifier-cube_split_1:tmp"
output_artifact_aliases: ["tmp"]
seed: null
device: "cuda"
eval_only_n_samples: null
dataset_split: "validation"
validate_artifacts: true
batch_size: ??? # set this in the command line
