hydra:
    searchpath:
        - file://extra/conf/global

defaults:
    - _self_
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog
    - override hydra/launcher: custom_slurm

trained_method_artifact_name: ??? # Need to specify for evaluation
cost_param: null
trained_classifier_artifact_name: ??? # Need to specify for evaluation
seed: null
device: "cuda"
eval_only_n_samples: null
dataset_split: "validation"
batch_size: ???
experiment_id: ""
