hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

method_artifact_path: ???
unmasker_type: ???
initializer_type: ???
dataset_artifact_path: ???
dataset_split: "testing"
classifier_artifact_path: null
seed: 42
device: "cuda"
n_selection_choices: 10
eval_only_n_samples: null
batch_size: 1
hard_budget: null
use_wandb: false
